### ISSUE TITLE
Can't authenticate with Google DRive

### ISSUE THREAD

**Issue by viseniv** [NiNiyas/autoscan#6] opened 2023-03-12 11:46 UTC
Whe i try to autherntiicate with Google Drive it gives me this error:
"Error 400: invalid_request"
I want to monitor a Team Drive, and send rclone to update the cache.

**Comment by NiNiyas** [comment] 2023-03-22 05:52
Hi. Sorry for taking so long to reply. I think this is probably because Autoscan still uses the OOB method to authenticate, which was [deprecated](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#disallowed-oob). Unfortunately, I don't have time to investigate this, but PRs are always welcome.

**Comment by TeJayH** [comment] 2023-12-06 10:36
A quick fix is to replace [this line](https://github.com/NiNiyas/autoscan/blob/master/google/drive.py#L121) in the /google/drive.py file

Change it from
`redirect_url = "urn:ietf:wg:oauth:2.0:oob"`
to
`redirect_url = "https://127.0.0.1"`

With this change when you auth successfully you'll get redirected to an empty localhost URL and you can just copy your auth code from the &code= section, so in this example, code would be ABC123 pasted into scan.py.
`https://127.0.0.1/?state=NONSENSEHERE&code=ABC123&scope=https://www.googleapis.com/auth/drive`

Not making it a proper PR because this is a pretty terrible way to do it, _I just don't know the proper way_, we can wait for someone who actually knows the modern gdrive api to do a proper fix but until then I can confirm this change makes the script functional for google drive again.

![totermw_IONioPEAgZ](https://github.com/NiNiyas/autoscan/assets/77415944/809afa13-6b45-4c2b-8886-7d9ea5d84aeb)
![2](https://github.com/NiNiyas/autoscan/assets/77415944/59444b6c-5c6d-449e-8075-86a33647560a)

**Comment by NiNiyas** [comment] 2024-07-11 07:31
Hey, this should now be fixed in the [alpha](https://github.com/NiNiyas/autoscan/tree/alpha) branch. Could you please give that a try? If you are on docker, use `ghcr.io/niniyas/autoscan:alpha_amd64` or `ghcr.io/niniyas/autoscan:alpha_arm64`, and don't forget to read the updated [readme](https://github.com/NiNiyas/autoscan/blob/alpha/README.md).

**Closed as completed** 2024-08-17 07:20 UTC
